targets:
  $default:
    builders:
      gisila_orm|schemaBuilder:
        generate_for:
          include:
            - lib/**.gisila.yaml
            - lib/**.gisila.yml
            - test/**.gisila.yaml
            - test/**.gisila.yml
            - example/**.gisila.yaml
            - example/**.gisila.yml
        enabled: true

builders:
  schemaBuilder:
    import: "package:gisila_orm/generators/schema_builder.dart"
    builder_factories: ["schemaBuilder"]
    build_extensions:
      ".gisila.yaml":
        - ".gisila.g.dart"
        - ".gisila.up.sql"
        - ".gisila.down.sql"
      ".gisila.yml":
        - ".gisila.g.dart"
        - ".gisila.up.sql"
        - ".gisila.down.sql"
    auto_apply: dependents
    build_to: source
