name: gisila_orm
description: Dart simple orm for postgress
version: 0.0.1+6
repository: https://github.com/gumisofts/gisila

environment:
  sdk: ^3.3.3
# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  args: ^2.4.2
  build: ^2.4.1
  dart_style: ">=3.0.0 <4.0.0"
  postgres: ^3.1.2
  source_span: ^1.10.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.0
  very_good_analysis: ^5.1.0
